config/urls.py
from django.contrib import admin
from django.urls import path, include
from core.homepage.views import IndexView
from core.login.views import *

from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404
from core.erp.views.dashboard.views import page_not_found404

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('login/', include('core.login.urls')),
    path('admin/', admin.site.urls),
    path('erp/', include('core.erp.urls')),
    path('reports/', include('core.reports.urls')),
    path('user/', include('core.user.urls')),
    
]

handler404 = page_not_found404

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/erp/urls.py
from django.urls import path
from core.erp.views.category.views import *
from core.erp.views.dashboard.views import *
from core.erp.views.product.views import *
from core.erp.views.test.views import TestView
from core.erp.views.client.views import *
from core.erp.views.sale.views import *

app_name = 'erp'

urlpatterns = [
    # Catehory
    path('category/list/', CategoryListView.as_view(), name='categoryList'),
    path('category/add/', CategoryCreateView.as_view(), name='categoryCreate'),
    path('category/update/<int:pk>/', CategoryUpdateView.as_view(), name='categoryUpdate'),
    path('category/delete/<int:pk>/', CategoryDeleteView.as_view(), name='categoryDelete'),
    # client
    path('client/list/', ClientListView.as_view(), name='clientList'),
    path('client/add/', ClientCreateView.as_view(), name='clientCreate'),
    path('client/update/<int:pk>/', ClientUpdateView.as_view(), name='clientUpdate'),
    path('client/delete/<int:pk>/', ClientDeleteView.as_view(), name='clientDelete'),
    # product
    path('product/list/', ProductListView.as_view(), name='productList'),
    path('product/add/', ProductCreateView.as_view(), name='productCreate'),
    path('product/update/<int:pk>/', ProductUpdateView.as_view(), name='productUpdate'),
    path('product/delete/<int:pk>/', ProductDeleteView.as_view(), name='productDelete'),
    # Home
    path('dashboard/', dashBoardView.as_view(), name='dashboard'),
    # Test
    path('test/', TestView.as_view(), name='test'),
    # Sale
    path('sale/list/', SaleListView.as_view(), name='saleList'),
    path('sale/add/', SaleCreateView.as_view(), name='saleCreate'),
    path('sale/update/<int:pk>/', SaleUpdateView.as_view(), name='saleUpdate'),
    path('sale/delete/<int:pk>/', SaleDeleteView.as_view(), name='saleDelete'),
    path('sale/invoice/pdf/<int:pk>/', SaleInvoicePdfView.as_view(), name='saleInvoicePdf'),
    

]

core/user/urls.py
from django.urls import path
from core.user.views import *

app_name = 'user'

urlpatterns = [
    # User
    path('list/', UserListView.as_view(), name='userList'),
    path('add/', UserCreateView.as_view(), name='userCreate'),
    path('update/<int:pk>/', UserUpdateView.as_view(), name='userUpdate'),
    path('delete/<int:pk>/', UserDeleteView.as_view(), name='userDelete'),
    path('change/group/<int:pk>/', UserChangeGroup.as_view(), name='userChangeGroup'),
    path('profile/', UserProfileView.as_view(), name='userProfile'),
    path('change/password/', UserChangePasswordView.as_view(), name='userChangePassword'),
]

templates/vtc/body.html
{% extends 'home.html' %}
{% block body %}
    <body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">
        <!-- Header -->
        {% include 'vtc/header.html' %}
        <!-- Sidebar -->
        {% include 'vtc/sidebar.html' %}
        <!-- Content -->
        <div class="content-wrapper">
            <div class="content-header">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-sm-6">
                            <h1 class="m-0 text-dark"> Bienvenido <small>{{ request.user.get_full_name }}</small></h1>
                        </div>
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-right">
                                <li class="breadcrumb-item"><a href="{% url 'erp:dashboard' %}">Inicio</a></li>
                                <li class="breadcrumb-item"><a href="{{ list_url }}">{{ entity }}</a></li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content">
                <div class="container-fluid">
                    {% block content %}

                    {% endblock %}
                </div>
            </div>
        </div>
        <!-- Footer -->
        {% include 'footer.html' %}
    </div>
    <!-- Block javascript -->
    {% block javascript %}

    {% endblock %}

    <script>
        {% if messages %}
            let html = '<p>';
            {% for message in messages %}
                html +='{{ message }}<br>';
            {% endfor %}
            html +='</p>';
            Swal.fire({
                title: 'Error!',
                html: html,
                icon: 'error'
            });
        {% endif %}
    </script>
    </body>
{% endblock %}

templates/vtc/header.html
<nav class="main-header navbar navbar-expand navbar-dark navbar-primary">
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="{% url 'erp:dashboard' %}" class="nav-link">Inicio</a>
        </li>
    </ul>
    <ul class="order-1 order-md-3 navbar-nav navbar-no-expand ml-auto">
        {% if request.user.groups.all %}
            <li class="nav-item dropdown">
                <a id="dropdownSubMenu1" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
                   class="nav-link{% if request.user.groups.all.count > 1 %} dropdown-toggle{% endif %}">{{ request.session.group }}</a>
                {% if request.user.groups.all.count > 1 %}
                    <ul aria-labelledby="dropdownSubMenu1" class="dropdown-menu border-0 shadow"
                        style="left: 0px; right: inherit;">
                        {% for g in request.user.groups.all %}
                            {% if g.id != request.session.group.id %}
                                <li><a href="{% url 'user:userChangeGroup' g.id %}"
                                       class="dropdown-item">{{ g.name }} </a></li>
                            {% endif %}
                        {% endfor %}
                    </ul>
                {% endif %}
            </li>
        {% endif %}
        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="fas fa-users-cog"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                <span class="dropdown-header">
                    Último Acceso: {{ request.user.last_login }}
                </span>
                <div class="dropdown-divider"></div>
                <a href="{% url 'user:userProfile' %}" class="dropdown-item">
                    <i class="fas fa-edit mr-2"></i> Editar perfil
                    <span class="float-right text-muted text-sm">3 mins</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="{% url 'user:userChangePassword' %}" class="dropdown-item">
                    <i class="fas fa-lock mr-2"></i> Editar password
                    <span class="float-right text-muted text-sm">12 hours</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item dropdown-footer">
                    <p>Este sistema te permitira realizar diferentes actividades</p>
                </a>
            </div>

        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">
                <i class="fas fa-power-off" aria-hidden="true"></i>
            </a>
        </li>
    </ul>
</nav>

templates/vtc/sidebar.html
{% load static %}
<aside class="main-sidebar sidebar-light-primary elevation-4">
    <a href="{% url 'erp:dashboard' %}" class="brand-link">
        <img src="{% static 'img/favicon.jpeg' %}"
             alt="AdminLTE Logo"
             class="brand-image img-circle elevation-3"
             style="opacity: .8">
        <span class="brand-text font-weight-light">Motos JDA</span>
    </a>
    <div class="sidebar">
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                <img src="{{ request.user.get_image }}" class="img-circle elevation-2" alt="User Image">
            </div>
            <div class="info">
                <a href="#" class="d-block">{{ request.user.username }}</a>
            </div>
        </div>
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <li class="nav-header">Mantenimientos</li>
                <li class="nav-item">
                    <a href="{% url 'erp:categoryList' %}" class="nav-link">
                        <i class="nav-icon fas fa-truck-loading"></i>
                        <p>
                            Categorías
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'erp:productList' %}" class="nav-link">
                        <i class="nav-icon fas fa-boxes"></i>
                        <p>
                            Productos
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'erp:clientList' %}" class="nav-link">
                        <i class="nav-icon fas fa-users"></i>
                        <p>
                            Clientes
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'erp:saleList' %}" class="nav-link">
                        <i class="nav-icon fas fa-shopping-cart"></i>
                        <p>
                            Ventas
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'saleReport' %}" class="nav-link">
                        <i class="nav-icon fas fa-chart-bar"></i>
                        <p>
                            Reporte De Ventas
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'user:userList' %}" class="nav-link">
                        <i class="nav-icon fas fa-user-friends"></i>
                        <p>
                            Usuarios
                        </p>
                    </a>
                </li>
            </ul>
        </nav>
    </div>
</aside>